{
 "title": "Logs Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Application Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "OtelTest.ServerOne Log entries by Severity",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "search source=otel\n| where serviceName=\"OtelTest.ServerOne\"\n| stats count() by severityText",
     "timeField": "time"
    }
   ]
  },
  {
   "title": "OtelTest.ServerOne Logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 1 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "search source=otel\n| where serviceName=\"OtelTest.ServerOne\"",
     "timeField": "time"
    }
   ]
  },
  {
   "title": "OtelTest.ServerTwo Log entries by Severity",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 9 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "search source=otel\n| where serviceName=\"OtelTest.ServerTwo\"\n| stats count() by severityText",
     "timeField": "time"
    }
   ]
  },
  {
   "title": "OtelTest.ServerOne Logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 9 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "search source=otel\n| where serviceName=\"OtelTest.ServerOne\"",
     "timeField": "time"
    }
   ]
  },
  {
   "title": "OtelTest.Client Log entries by Severity",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 17 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "search source=otel\n| where serviceName=\"OtelTest.Client\"\n| stats count() by severityText",
     "timeField": "time"
    }
   ]
  },
  {
   "title": "OtelTest.Client Logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 17 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "search source=otel\n| where serviceName=\"$OtelTest.Client\"",
     "timeField": "time"
    }
   ]
  },
  { "title": "Application Meters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Latexiron Meters",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    { "expr": "latexiron_days_freezing_total", "legendFormat": "__auto" },
    { "expr": "latexiron_days_updown", "legendFormat": "__auto" },
    {
     "expr": "latexiron_questions_clever_The_number_of_times_someone_has_asked_this_server_an_intelligent_question_total",
     "legendFormat": "__auto"
    },
    {
     "expr": "latexiron_questions_stupid_The_number_of_tiems_someone_has_asked_this_server_a_stupid_question_total",
     "legendFormat": "__auto"
    },
    { "expr": "latexiron_server_checks_total", "legendFormat": "__auto" },
    { "expr": "latexiron_server1_calls_total", "legendFormat": "__auto" }
   ]
  }
 ]
}